### ISSUE TITLE
Application error: a client-side exception has occurred (see the browser console for more information).

### ISSUE THREAD

**Issue by mikeyang01** [ndimatteo/HULL#134] opened 2023-12-24 10:17 UTC
open https://hull.dev/
shows
Application error: a client-side exception has occurred (see the browser console for more information).

**Comment by ndimatteo** [comment] 2023-12-24 19:24
@mikeyang01 this sounds like a duplicate of #128. I cannot replicate this in any of the latest versions of common browsers (Chrome, Safari, or Firefox).

Please provide more details if you have any. Otherwise, as mentioned in the other issue, I'll be making some updates in the new year that will remove the package that this error originates from.

**Comment by nimser** [comment] 2024-02-02 16:28
For info in case useful to someone. This occurs on the homepage, on a vanilla install of Brave browser and seems related to the GoogleTagManager (see my comment [here](https://github.com/ndimatteo/HULL/issues/128#issuecomment-1920166562))

**Closed as completed** 2024-02-03 06:16 UTC
Labels: needs info
